apiVersion: v1
kind: Secret
metadata:
  name: database-url-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3dlbGxuZXNzX293bmVyOlUzTGRsbXJjSVI4ZUBlcC1yb3VuZC1kcmVhbS1h
NTYzeXhicS51cy1lYXN0LTIuYXdzLm5lb24udGVjaC93ZWxsbmVzcz9zc2xtb2RlPXJlcXVpcmU=
